apiVersion: v1
kind: Service
metadata:
  labels:
    app: apihub-apicurio
  name: apihub-apicurio
spec:
  ports:
  - name: "8080"
    nodePort: 42080
    port: 8080
    targetPort: 8080
  selector:
    app: apihub-apicurio
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apihub-apicurio
  name: apihub-apicurio
spec:
  selector:
    matchLabels:
      app: apihub-apicurio
  template:
    metadata:
      labels:
        app: apihub-apicurio
      name: apihub-apicurio
    spec:
      containers:
      - name: apihub-apicurio
        image: apicurio/apicurio-registry-mem:2.2.4.Final
        ports:
          - containerPort: 8080
            hostPort: 7080
        env:
        - name: QUARKUS_PROFILE
          value: prod