apiVersion: v1
kind: Service
metadata:
  labels:
    app: apihub-kong
  name: apihub-kong
spec:
  ports:
  - name: "8000"
    nodePort: 48000
    port: 8000
    targetPort: 8000
  - name: "8443"
    nodePort: 48443
    port: 8443
    targetPort: 8443
  - name: "8001"
    nodePort: 48001
    port: 8001
    targetPort: 8001
  - name: "8444"
    nodePort: 48444
    port: 8444
    targetPort: 8444
  selector:
    app: apihub-kong
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apihub-kong
  name: apihub-kong
spec:
  selector:
    matchLabels:
      app: apihub-kong
  template:
    metadata:
      annotations:
        io.podman.annotations.ulimit: nofile=524288:524288,nproc=46448:46448
      labels:
        app: apihub-kong
      name: apihub-kong
    spec:
      containers:
      - name: apihub-kong
        image: kong:2.8.1-alpine
        ports:
          - containerPort: 8000
          - containerPort: 8443
          - containerPort: 8001
          - containerPort: 8444
        env:
        - name: KONG_DATABASE
          value: off
        - name: KONG_DECLARATIVE_CONFIG
          value: /kong/declarative/kong.yml
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        volumeMounts:
          - mountPath: /kong/declarative/kong.yml
            name: kong-config-file
      volumes:
        - hostPath:
            path: ./kong/kong.yml
            type: File
          name: kong-config-file