apiVersion: v1
kind: Service
metadata:
  labels:
    app: apihub-postgres
  name: apihub-postgres
spec:
  ports:
  - name: "5432"
    nodePort: 31321
    port: 5432
    targetPort: 5432
  selector:
    app: apihub-postgres
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apihub-postgres
  name: apihub-postgres
spec:
  selector:
    matchLabels:
      app: apihub-postgres
  template:
    metadata:
      annotations:
        io.podman.annotations.ulimit: nofile=524288:524288,nproc=46448:46448
      labels:
        app: apihub-postgres
      name: apihub-postgres
    spec:
      containers:
      - args:
        - postgres
        env:
        - name: POSTGRES_PASSWORD
          value: apihub
        - name: POSTGRES_USER
          value: apihub
        image: docker.io/library/postgres:14
        name: apihub-postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init-user-dbs.sql
          name: init_user_dbs.sql
        - mountPath: /var/lib/postgresql/data
          name: ba5b6b1b3069c6f65f9b01601f689c26891d8735ed069e7439ad395ca35e35e8-pvc
      volumes:
      - hostPath:
          path: ./init_user_dbs.sql
          type: File
        name: init_user_dbs.sql
      - name: ba5b6b1b3069c6f65f9b01601f689c26891d8735ed069e7439ad395ca35e35e8-pvc
        persistentVolumeClaim:
          claimName: ba5b6b1b3069c6f65f9b01601f689c26891d8735ed069e7439ad395ca35e35e8
