apiVersion: v1
kind: Service
metadata:
  labels:
    app: apihub-vault
  name: apihub-vault
spec:
  ports:
  - name: "8200"
    nodePort: 38200
    port: 8200
    targetPort: 8200
  selector:
    app: apihub-vault
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apihub-vault
  name: apihub-vault
spec:
  selector:
    matchLabels:
      app: apihub-vault
  template:
    metadata:
      labels:
        app: apihub-vault
      name: apihub-vault
    spec:
      containers:
      - name: apihub-vault
        image: vault:1.10.4
        ports:
          - containerPort: 8200
        env:
        - name: VAULT_ADDR
          value: http://0.0.0.0:8200
        cap_add:
          - IPC_LOCK