quarkus:
  datasource:
    db-kind: pg
    health:
      enabled: true
  kafka:
    health:
      enabled: true

mp:
  messaging:
    incoming:
      client-updates:
        connector: smallrye-kafka
        group:
          id: gw
        topic: "client-updates"
        auto:
          offset:
            reset: earliest
        value:
          deserializer: org.apache.kafka.common.serialization.DoubleDeserializer
        broadcast: true
        failure-strategy: dead-letter-queue
        health-enabled: true
    outgoing:
      billing:
        connector: smallrye-kafka
        topic: billing
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
